<?php

/**
 * PictureTag
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Tagcloud server for images.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */
namespace OpenAPIServer\Api;

use Psr\Container\ContainerInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;
use Slim\Exception\HttpNotImplementedException;

/**
 * AbstractTagApi Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
abstract class AbstractTagApi
{

    /**
     * @var ContainerInterface|null Slim app container instance
     */
    protected $container;

    /**
     * Route Controller constructor receives container
     *
     * @param ContainerInterface|null $container Slim app container instance
     */
    public function __construct(ContainerInterface $container = null)
    {
        $this->container = $container;
    }


    /**
     * POST addTag
     * Summary: Add a new tag to the tagcloud
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function addTag(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $body = $request->getParsedBody();
        $message = "How about implementing addTag as a POST method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * DELETE deleteTag
     * Summary: Deletes a tag
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function deleteTag(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $name = $args['name'];
        $message = "How about implementing deleteTag as a DELETE method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET findTagsByAuthor
     * Summary: Finds Tags by author
     * Output-Formats: [application/json, application/xml]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function findTagsByAuthor(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $author = $args['author'];
        $message = "How about implementing findTagsByAuthor as a GET method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getTagByTagName
     * Summary: Find Tag by TangName
     * Notes: Returns a single Tag
     * Output-Formats: [application/json, application/xml]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTagByTagName(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $name = $args['name'];
        $message = "How about implementing getTagByTagName as a GET method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * GET getTagListing
     * Summary: Lists availlable Tags
     * Output-Formats: [application/json, application/xml]
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function getTagListing(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $message = "How about implementing getTagListing as a GET method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }

    /**
     * PUT updateTag
     * Summary: Update an existing tag
     *
     * @param ServerRequestInterface $request  Request
     * @param ResponseInterface      $response Response
     * @param array|null             $args     Path arguments
     *
     * @return ResponseInterface
     * @throws HttpNotImplementedException to force implementation class to override this method
     */
    public function updateTag(ServerRequestInterface $request, ResponseInterface $response, array $args)
    {
        $body = $request->getParsedBody();
        $message = "How about implementing updateTag as a PUT method in OpenAPIServer\Api\TagApi class?";
        throw new HttpNotImplementedException($request, $message);
    }
}
