<?php

/**
 * PictureTag
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Tagcloud server for images.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\ImageApi;

/**
 * ImageApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\ImageApi
 */
class ImageApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getImagesByTagName
     *
     * Find Images by TangName.
     *
     * @covers ::getImagesByTagName
     */
    public function testGetImagesByTagName()
    {
        $this->markTestIncomplete(
            'Test of "getImagesByTagName" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getNextImage
     *
     * Find next image.
     *
     * @covers ::getNextImage
     */
    public function testGetNextImage()
    {
        $this->markTestIncomplete(
            'Test of "getNextImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getPreviousImage
     *
     * Find previous image.
     *
     * @covers ::getPreviousImage
     */
    public function testGetPreviousImage()
    {
        $this->markTestIncomplete(
            'Test of "getPreviousImage" method has not been implemented yet.'
        );
    }
}
