<?php

/**
 * PictureTag
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Tagcloud server for images.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\TagApi;

/**
 * TagApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\TagApi
 */
class TagApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addTag
     *
     * Add a new tag to the tagcloud.
     *
     * @covers ::addTag
     */
    public function testAddTag()
    {
        $this->markTestIncomplete(
            'Test of "addTag" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteTag
     *
     * Deletes a tag.
     *
     * @covers ::deleteTag
     */
    public function testDeleteTag()
    {
        $this->markTestIncomplete(
            'Test of "deleteTag" method has not been implemented yet.'
        );
    }

    /**
     * Test case for findTagsByAuthors
     *
     * Finds Tags by author.
     *
     * @covers ::findTagsByAuthors
     */
    public function testFindTagsByAuthors()
    {
        $this->markTestIncomplete(
            'Test of "findTagsByAuthors" method has not been implemented yet.'
        );
    }

    /**
     * Test case for findTagsByImage
     *
     * Finds Tags by image.
     *
     * @covers ::findTagsByImage
     */
    public function testFindTagsByImage()
    {
        $this->markTestIncomplete(
            'Test of "findTagsByImage" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getInventory
     *
     * Returns Tags.
     *
     * @covers ::getInventory
     */
    public function testGetInventory()
    {
        $this->markTestIncomplete(
            'Test of "getInventory" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getTagByTagName
     *
     * Find Tag by TangName.
     *
     * @covers ::getTagByTagName
     */
    public function testGetTagByTagName()
    {
        $this->markTestIncomplete(
            'Test of "getTagByTagName" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateTag
     *
     * Update an existing ta.
     *
     * @covers ::updateTag
     */
    public function testUpdateTag()
    {
        $this->markTestIncomplete(
            'Test of "updateTag" method has not been implemented yet.'
        );
    }
}
