<?php

/**
 * PictureTag
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Tagcloud server for images.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Note;

/**
 * NoteTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Note
 */
class NoteTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Note"
     */
    public function testNote()
    {
        $testNote = new Note();
        $namespacedClassname = Note::getModelsNamespace() . '\\Note';
        $this->assertSame('\\' . Note::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Note" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
        $this->markTestIncomplete(
            'Test of "author" property in "Note" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
        $this->markTestIncomplete(
            'Test of "note" property in "Note" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
        $this->markTestIncomplete(
            'Test of "date" property in "Note" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Note::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
