<?php

/**
 * PictureTag
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample Tagcloud server for images.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Tag;

/**
 * TagTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Tag
 */
class TagTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Tag"
     */
    public function testTag()
    {
        $testTag = new Tag();
        $namespacedClassname = Tag::getModelsNamespace() . '\\Tag';
        $this->assertSame('\\' . Tag::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "originalImageId"
     */
    public function testPropertyOriginalImageId()
    {
        $this->markTestIncomplete(
            'Test of "originalImageId" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "imageIds"
     */
    public function testPropertyImageIds()
    {
        $this->markTestIncomplete(
            'Test of "imageIds" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $this->markTestIncomplete(
            'Test of "name" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "author"
     */
    public function testPropertyAuthor()
    {
        $this->markTestIncomplete(
            'Test of "author" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
        $this->markTestIncomplete(
            'Test of "notes" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
        $this->markTestIncomplete(
            'Test of "date" property in "Tag" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Tag::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
